### ISSUE TITLE
[Installation bug] incompatible versions of tensorflow

### ISSUE THREAD

**Issue by HippolyteKarakostas** [ml4astro/galaxy2galaxy#27]
#### Issue description
Attempt to install the Git repository "Galaxy2Galaxy" on macOS Catalina version 10.15.3 (MacBook Pro).
The following line code is expected to work,

```bash
g2g-datagen --problem=img2img_cosmos --data_dir=data/img2img_cosmos
```
but an error occurs.

#### Steps to reproduce the issue

1.  Open a terminal

2. clone the Git repository: 
```bash
git clone https://github.com/ml4astro/galaxy2galaxy.git
```
3. Create an anaconda environment running on python 3.6:  
```bash
conda create --name G2G python=3.6
```
4. Activate the new environment: 
```bash
conda activate G2G
```
5. Install galsim: 
```bash
 conda install -c conda-forge galsim 
```
6. Change directory to galaxy2galaxy:

7. Execute the command line: 
```bash
pip install --user -e.
```
8. install tensorflow version 1.15: 
```bash
conda install -c conda-forge tensorflow=1.15
```

9. change directory : 
```bash
cd galaxy2galaxy/galaxy2galaxy/bin
```

10. execute command line: 
```bash
python g2g-datagen --problem=img2img_cosmos --data_dir=data/img2img_cosmos
```

#### What's the expected result?

- No errors

#### What's the actual result?

- error: 
```bash 
ModuleNotFoundError: No module named 'tensorflow.contrib'
```

**Comment by EiffL** [comment]
Hey @HippolyteKarakostas , I have updated a bunch of things, it should work if you follow the steps on the README. Could you start from a fresh conda env?

**Comment by EiffL** [comment]
We resolved that issue, which was caused by a recent update of one of the T2T dependencies. Many thanks @HippolyteKarakostas
